spring:
  datasource:
    url: jdbc:mysql://faq-service-server.mysql.database.azure.com:3306/faq-service-database
    username: vayemxvcqu
    password: Hz$U8OwUuPYYACqa
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
